# Site settings
title: Loading's Blog
tagline: 
email: luodin2013@gmail.com
description: Loading...
browser_title: Loading...
banner_image: 'assets/images/sample-banner-image-1.jpg'
baseurl: "" # the subpath of your siimte, e.g. /blog/
url: "http://luoding.me"
# url: "http://127.0.0.1:4002" # the base hostname & protocol for your site
#logourl: /assets/images/logo.png # Site logo
author: "Loading"
author_thumbnail: "/assets/images/avatar.png" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  #highlight_color: "#205081" #205081" # "#272935"
  highlighter: rouge
  # Social media links, leave blank to ignore
  social: 
    github: https://github.com/luodin007/luodin007.github.io


  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: Loading

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
    input: GFM

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
